


DROP TABLE IF EXISTS Students;
CREATE TABLE Students(
FirstName VARCHAR(100),
LastName VARCHAR(100),
Student_ID INTEGER PRIMARY KEY AUTOINCREMENT
);

DROP TABLE IF EXISTS Quizzes;
CREATE TABLE Quizzes(
Quiz_ID INTEGER PRIMARY KEY AUTOINCREMENT,
Quiz_Name VARCHAR(100),

Question_Number INT,
Quiz_Date TEXT
);

DROP TABLE IF EXISTS Results;
CREATE TABLE Results(
Student_ID INT,
Quiz_ID INT,
Grade INT
);


